"use client";

import { useState } from "react";
import { Check } from "lucide-react";

interface ConsentFormProps {
  onConsent: (consentGiven: boolean) => void;
}

export default function ConsentForm({ onConsent }: ConsentFormProps) {
  const [consentChecked, setConsentChecked] = useState(false);
  const [hasRead, setHasRead] = useState(false);

  const handleSubmit = () => {
    if (consentChecked) {
      onConsent(true);
    }
  };

  return (
    <div className="min-h-screen claude-bg flex items-center justify-center p-4">
      <div className="max-w-4xl w-full">
        <div className="claude-card shadow-lg p-8">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold claude-text mb-2">
              Informed Consent
            </h1>
            <p className="text-muted">
              Please read the following information carefully before
              participating in this study.
            </p>
          </div>

          <div className="claude-secondary rounded-lg p-6 mb-8 max-h-96 overflow-y-auto">
            <div className="prose prose-sm max-w-none">
              <h2 className="text-xl font-semibold mb-4 claude-text">
                Informed Consent of Study Participation
              </h2>
              <p className="mb-4 text-muted">
                You are invited to participate in the online study &quot;Evaluating
                User Perception of LLM Output Quality Across Cognitive Task
                Types&quot;. The study is conducted by Hamza Asaad, Muhammad Hamza
                Laghari, Danish Ali, and Muhammad Furqan Shafique and supervised
                by Prof. Dr. Valentin Schwind from the Frankfurt University of
                Applied Sciences. The study with estimated 20 participants takes
                place in the period from 2025-08-06 to 2025-08-25. Please note:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1 text-muted">
                <li>
                  Your participation is entirely voluntary and can be
                  discontinued or withdrawn at any time
                </li>
                <li>
                  One session of the online study will last ca. 20 minutes
                </li>
                <li>
                  As compensation for your participation, you will receive one
                  credit point for the lecture
                </li>
                <li>
                  For the evaluation, we collect some of personal information
                  (e.g., age, gender, etc.), whereas contact data (e.g. e-mails)
                  will only be used for feedback or further information about
                  the study and not be passed on to any third parties
                </li>
                <li>
                  During the session, we will log your input and manually record
                  notes
                </li>
                <li>
                  Recordings and personal data are subject to the guidelines of
                  the General Data Protection Regulation (GDPR) and will
                  pseudoanonymized (with a coded number) stored, evaluated and
                  possibly made publicly available as raw data sets so that
                  without information from the researchers no conclusions can be
                  drawn about individual persons
                </li>
              </ul>
              <p className="mb-4 text-muted">
                The alternative to participation in this study is to choose not
                to participate. If you have any questions, concerns, or
                complaints about the informed consent process of this research
                study or your rights as a human research subject, please contact
                Prof. Dr. Valentin Schwind. Please read the following
                information carefully and take the time you need.
              </p>

              <h3 className="text-lg font-medium mb-2 claude-text">
                1. Purpose and Goal of this Research
              </h3>
              <p className="mb-4 text-muted">
                This research investigates how users perceive and evaluate the
                quality of responses generated by large language models (LLMs)
                across different types of tasks. The goal is to understand which
                kinds of tasks LLMs perform well or poorly in and how users
                identify and interpret potential quality issues in LLM outputs
                Your participation will help us achieve this research goal. The
                results of this research may be presented at scientific or
                professional meetings or published in scientific proceedings and
                journals.
              </p>

              <h3 className="text-lg font-medium mb-2 claude-text">
                2. Study Participation
              </h3>
              <p className="mb-4 text-muted">
                Your participation in this online study is entirely voluntary
                and can be discontinued or withdrawn at any time. You can refuse
                to answer any questions or continue with the study at any time
                if you feel uncomfortable in any way. You can discontinue or
                withdraw your participation at any time without giving a reason.
                However, we reserve the right to exclude you from the study
                (e.g., with invalid trials or if continuing the study could have
                a negative impact on your well-being or the equipment).You will
                also receive the compensation offered if you discontinue study
                participation. Repeated participation in the study is not
                permitted.
              </p>

              <h3 className="text-lg font-medium mb-2 claude-text">
                3. Study Procedure
              </h3>
              <p className="mb-4 text-muted">
                After confirming this informed consent the procedure is as
                follows:
              </p>
              <ol className="list-decimal pl-6 mb-4 space-y-1 text-muted">
                <li>
                  You will first read a brief overview of the study and give
                  your consent to participate.
                </li>
                <li>
                  You will receive instructions on how to interact with an LLM
                  to complete a series of short tasks.
                </li>
                <li>
                  You will complete 8 tasks in total, grouped into 4 different
                  types. The order of these tasks may vary.
                </li>
                <li>
                  For each task, you will type a prompt to get a response from
                  the LLM, and you may revise your prompt if the response is not
                  helpful.
                </li>
                <li>
                  After each task, you will answer a short multiple-choice
                  question about your satisfaction with the LLM&apos;s response.
                </li>
                <li>
                  Once all tasks are finished, you will complete a brief survey
                  about your overall experience.
                </li>
                <li>
                  During the study, your prompts, the LLM&apos;s responses, and the
                  time you take will be recorded.
                </li>
                <li>
                  The entire session will take about 20 minutes. After that, the
                  study ends and you will be shown a debriefing message.
                </li>
              </ol>
              <p className="mb-4 text-muted">
                The confirmation of participation in this study can be obtained
                directly from the researchers.
              </p>

              <h3 className="text-lg font-medium mb-2 claude-text">
                4. Risks and Benefits
              </h3>
              <p className="mb-4 text-muted">
                In the online study you will not be exposed to any immediate
                risk or danger. As with all computer systems on which data is
                processed, despite security measures, there is a small risk of
                data leakage and the loss of confidential or personal
                information. As compensation for your participation, you will
                receive one credit point for the lecture. With your
                participation you support our research work and contribute to a
                better understanding of human-computer interaction.
              </p>

              <h3 className="text-lg font-medium mb-2 claude-text">
                5. Data Protection and Confidentiality
              </h3>
              <p className="mb-4 text-muted">
                In this study, personal and personal data are collected for our
                research. The use of personal or subject-related information is
                governed by the European Union (EU) General Data Protection
                Regulation (GDPR) and will be treated in accordance with the
                GDPR. This means that you can view, correct, restrict
                processing, and delete the data collected in this study. Only
                with your agreement, we will log your input and manually record
                notes in the study. We plan to publish the results of this and
                other research studies in academic articles or other media. Your
                data will not be retained for longer than necessary or until you
                contact researchers to have your data destroyed or deleted.
                Access to the raw data, transcribed interviews, and observation
                protocols of the study during the analysis is encrypted,
                password-protected and only accessible to the authors,
                colleagues, and researchers collaborating on this research. As
                part of the research, the data will be anonymized using code
                numbers and then be made available to the general public,
                whereas without information from the researchers no conclusions
                can be drawn about individual persons. Once the material has
                been made publicly available, the distribution of the data can
                no longer be revoked. Any interview content or direct quotations
                from the interview, that are made available through academic
                publications or other academic outlets will also be anonymized
                using code numbers. Contact details (e.g. e-mails) will not be
                passed on to third parties, but may be used by the researchers
                to contact participants, trace infection chains, or to send you
                further details of the study. According to the GDPR, the
                researchers will inform the participants using their contact
                details if a confidential data breach has been detected.
              </p>

              <h3 className="text-lg font-medium mb-2 claude-text">
                6. Identification of Investigators
              </h3>
              <p className="mb-4 text-muted">
                If you have any questions or concerns about the research, please
                feel free to contact:
              </p>
              <div className="bg-blue-50 p-4 rounded-lg mb-4">
                <p className="font-medium claude-text mb-2">Researchers</p>
                <p className="text-muted">
                  Hamza Asaad (hamza.asaad@stud.fra-uas.de)
                </p>
                <p className="text-muted">
                  Muhammad Hamza Laghari (muhammad.laghari@stud.fra-uas.de)
                </p>
                <p className="text-muted">
                  Danish Ali (danish.ali@stud.fra-uas.de)
                </p>
                <p className="text-muted">
                  Muhammad Furqan Shafique (muhammad.shafique@stud.fra-uas.de)
                </p>
                <p className="text-muted">
                  Frankfurt University of Applied Sciences
                </p>
              </div>
              <div className="bg-blue-50 p-4 rounded-lg">
                <p className="font-medium claude-text mb-2">
                  Principal investigator
                </p>
                <p className="text-muted">Prof. Dr. Valentin Schwind</p>
                <p className="text-muted">valentin.schwind@fra-uas.de</p>
                <p className="text-muted">
                  Frankfurt University of Applied Sciences
                </p>
                <p className="text-muted">Nibelungenplatz 1</p>
                <p className="text-muted">60318 Frankfurt am Main, Germany</p>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <input
                type="checkbox"
                id="hasRead"
                checked={hasRead}
                onChange={(e) => setHasRead(e.target.checked)}
                className="mt-1 w-4 h-4 text-primary border-border rounded focus:ring-primary"
              />
              <label htmlFor="hasRead" className="text-sm text-muted">
                I have read and understood the information provided above.
              </label>
            </div>

            <div className="flex items-start space-x-3">
              <input
                type="checkbox"
                id="consent"
                checked={consentChecked}
                onChange={(e) => setConsentChecked(e.target.checked)}
                disabled={!hasRead}
                className="mt-1 w-4 h-4 text-primary border-border rounded focus:ring-primary disabled:opacity-50"
              />
              <label htmlFor="consent" className="text-sm text-muted">
                I voluntarily agree to participate in this research study. I
                understand that I may withdraw at any time without penalty.
              </label>
            </div>
          </div>

          <div className="mt-8 flex justify-center">
            <button
              onClick={handleSubmit}
              disabled={!consentChecked || !hasRead}
              className="claude-primary px-8 py-3 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-2"
            >
              <Check className="w-5 h-5" />
              <span>I Agree to Participate</span>
            </button>
          </div>

          {!hasRead && (
            <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-md">
              <p className="text-sm text-blue-700">
                Please read through the consent information above before
                proceeding.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
